## Step 1:  Problem Statement 
Predict the purchase of product after showing the ads on social network 

## Step 2: Data Gathering 

In [1]:
import pandas as pd 
df = pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

## Step 3: EDA

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [3]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [4]:
df['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [5]:
df['Purchased'].value_counts()/ len(df) * 100


0    64.25
1    35.75
Name: Purchased, dtype: float64

In [6]:
This target columns in imbalance 
>> Solution >> SMOTE 

SyntaxError: invalid syntax (2073417868.py, line 1)

In [7]:
df['Gender'].value_counts().to_dict()

{'Female': 204, 'Male': 196}

### step 4 : Feature Engg 

In [8]:
df['Gender'].replace({'Female': 0, 'Male': 1}, inplace = True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    int64
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(5)
memory usage: 15.8 KB


### Step 5 : Feature Selection 

In [10]:
df.drop('User ID', axis = 1, inplace= True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    int64
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
dtypes: int64(4)
memory usage: 12.6 KB


### Scaling 

In [12]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split


In [13]:
x = df.drop('Purchased', axis = 1)
y = df['Purchased']

In [14]:
x_train, x_test, y_train,y_test = train_test_split(x,y, test_size=0.25, random_state=5, stratify=y)

In [15]:
std_scale = StandardScaler()
x_train_scale =std_scale.fit_transform(x_train) 

In [16]:
x_train_scale

array([[ 1.03390789e+00,  4.08925008e-01, -4.48543667e-01],
       [-9.67204152e-01,  3.15846478e-01,  8.86343773e-02],
       [-9.67204152e-01,  8.74317657e-01, -1.16478106e+00],
       [-9.67204152e-01,  1.43278884e+00,  3.87066624e-01],
       [ 1.03390789e+00, -1.08033147e+00,  3.57223400e-01],
       [ 1.03390789e+00, -7.08017350e-01,  1.13314724e+00],
       [ 1.03390789e+00, -1.26648853e+00, -1.49305653e+00],
       [-9.67204152e-01, -1.08033147e+00,  3.27380175e-01],
       [-9.67204152e-01, -5.21860290e-01,  2.41640590e+00],
       [ 1.03390789e+00,  2.08433854e+00, -8.06662363e-01],
       [-9.67204152e-01, -9.87252939e-01, -1.55274298e+00],
       [ 1.03390789e+00, -2.42624701e-01,  1.16299047e+00],
       [ 1.03390789e+00,  2.08433854e+00,  4.16909849e-01],
       [ 1.03390789e+00,  6.88160597e-01, -1.40352686e+00],
       [ 1.03390789e+00, -8.94174410e-01,  5.95969197e-01],
       [-9.67204152e-01, -1.73188118e+00, -1.28415396e+00],
       [ 1.03390789e+00, -8.01095880e-01

In [17]:
x_test_scale = std_scale.transform(x_test)

## Model Training

In [18]:
from sklearn.svm import SVC

In [19]:
model = SVC()
model.fit(x_train_scale, y_train)

SVC()

In [20]:
### Model EValuation 
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
y_pred = model.predict(x_test_scale)
y_pred

def model_eval(actual,pred):
    acc = accuracy_score(actual,pred)
    print(f"Accuracy Score = {acc}")
    
    cm = confusion_matrix(actual,pred)
    print(cm)
    
    cr = classification_report(actual, pred)
    print(cr)
    
    return "Success"
model_eval(y_test, y_pred)

Accuracy Score = 0.9
[[57  7]
 [ 3 33]]
              precision    recall  f1-score   support

           0       0.95      0.89      0.92        64
           1       0.82      0.92      0.87        36

    accuracy                           0.90       100
   macro avg       0.89      0.90      0.89       100
weighted avg       0.91      0.90      0.90       100



'Success'

In [21]:
### Training data evaluation 

y_pred = model.predict(x_train_scale)
model_eval(y_train,y_pred)

Accuracy Score = 0.9133333333333333
[[176  17]
 [  9  98]]
              precision    recall  f1-score   support

           0       0.95      0.91      0.93       193
           1       0.85      0.92      0.88       107

    accuracy                           0.91       300
   macro avg       0.90      0.91      0.91       300
weighted avg       0.92      0.91      0.91       300



'Success'

In [22]:
Bias == low 
Variance = low 

>> Generlised Model 

SyntaxError: invalid syntax (2550062123.py, line 4)

In [23]:
### Math Function >> Kernel Function  
1. Linear
2. Poly 
3. Rbf
4. sigmoid 

SyntaxError: invalid syntax (1606317473.py, line 2)

In [24]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import numpy as np

In [25]:

svc = SVC()
hyp = {
    "C" : np.arange(1,11),
    "kernel" : ['linear', 'poly','rbf','sigmoid']
}

gscv = GridSearchCV(svc, hyp, cv = 5)
gscv.fit(x_train_scale, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [26]:
gscv.best_params_

{'C': 6, 'kernel': 'rbf'}

In [27]:
op_model = SVC(C= 6, kernel='rbf')
op_model.fit(x_train_scale,y_train)

### Model Evalaution 
### Testing 
y_pred = op_model.predict(x_test_scale)
model_eval(y_test,y_pred)

### Training 
y_pred = op_model.predict(x_train_scale)
model_eval(y_train,y_pred)

Accuracy Score = 0.89
[[56  8]
 [ 3 33]]
              precision    recall  f1-score   support

           0       0.95      0.88      0.91        64
           1       0.80      0.92      0.86        36

    accuracy                           0.89       100
   macro avg       0.88      0.90      0.88       100
weighted avg       0.90      0.89      0.89       100

Accuracy Score = 0.92
[[177  16]
 [  8  99]]
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       193
           1       0.86      0.93      0.89       107

    accuracy                           0.92       300
   macro avg       0.91      0.92      0.91       300
weighted avg       0.92      0.92      0.92       300



'Success'

In [28]:
### User Defined 

gender = 'Male'
age = 35
salary = 50000

def predict(gender, age, salary):
    '''Predict function op_model '''
    
    # converting categorical data into numerical data 
    if gender == 'male'  or gender == "Male" or gender == "MALE" or gender == "M":
        gender = 1
    else: 
        gender = 0 
    
    ## Creating an array and scaling
    arr = np.array ([gender, age, salary])
    arr_scale = std_scale.transform([arr])
    predict = op_model.predict(arr_scale)
    predict

    if predict[0] == 0: 
        print(f"Not Purchsed the product")
    else: 
        print(f"Purchase the  Product")
        
    return predict[0]

predict(gender,age,salary)

Not Purchsed the product


C:\Users\Sahyadri\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


0

In [34]:
import pickle
with open("model.pickle","wb") as file:
    pickle.dump(op_model,file)

In [35]:
import pickle
with open("std.pickle","wb") as file:
    pickle.dump(std_scale,file)

In [42]:
import pickle
with open("model.pickle","rb") as file:
    a=pickle.load(file)

SVC(C=6)